###########################################################################
# Default settings for the consumer JAR
###########################################################################


###########################################################################
# Kafka settings
###########################################################################
kafka:
    bootstrap-servers: localhost:9092
    topic-name: updates