##########################################################
# Consumer application.yaml file
##########################################################



##########################################################
# Kafka Settings
##########################################################
kafka:
    bootstrap-servers:   b-3.democluster1.gh2mtx.c11.kafka.us-east-1.amazonaws.com:9098,b-1.democluster1.gh2mtx.c11.kafka.us-east-1.amazonaws.com:9098,b-2.democluster1.gh2mtx.c11.kafka.us-east-1.amazonaws.com:9098
    truststore-filepath: /tmp/truststore.jks